//
//
//  Generated by StarUML(tm) Java Add-In
//
//
//


/**
 * Adds to the current amount food a new value
 **/
public class Animal extends Organism {
    private double needEachWeek;
    private double eatenThisWeek;

    /**
     * Calls the base class constructor. Initialization of variables
     *
     * @param initRate
     * @param initSize
     * @param initNeed
     **/
    public Animal(double initRate, double initSize, double initNeed) {
        super(initRate, initSize);
        needEachWeek = initNeed;
    }

    /**
     * Calling a function from the superclass. Checks the adequacy of food eaten
     **/
    public void simulateWeek() {
        if (eatenThisWeek < needEachWeek) {
            alterSize(-getSize());
        } else {
            eatenThisWeek = 0;
        }
    }

    public double getNeed() {
        return needEachWeek;
    }

    public void setNeed(double newNeed) {

        needEachWeek = newNeed;
    }

    /**
     * Returns the necessary amount of food for this week
     **/
    public double stillNeed() {
        return needEachWeek - eatenThisWeek;
    }

    public void eat(double amount) {
        /*TODO*/
        eatenThisWeek += amount;
    }
}
