//
//
//  Generated by StarUML(tm) Java Add-In
public class Herbivore extends Animal {
    public Herbivore(double initRate, double initSize, double initNeed) {
        super(initRate, initSize, initNeed);
    }

    public void nibble(Plant meal) {
        double eaten = meal.getSize() * 0.5;
        if (eaten > this.getNeed() / 10) {
            eaten = this.getNeed()/10;
        }
        if (eaten > this.stillNeed()){
            eaten = stillNeed();
        }
        eat(eaten);
        meal.alterSize(-eaten);
    }
}
