//
//
//  Generated by StarUML(tm) Java Add-In
//
//
//

/**
 * Calls parent's constructor
 **/
public class Plant extends Organism {
    /**
     * Calls parent's constructor
     *
     * @param initRate
     * @param initSize
     **/
    public Plant(double initRate, double initSize) {
        super(initRate, initSize);
    }

    /**
     * Calls alterSize with negative value
     *
     * @param amount
     **/
    public void nibbledOn(double amount) {
        alterSize(-amount);
    }
}
